package tools

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"darci-go/darci/config"
)

// NotebookCreateTool creates a new engineering notebook entry
type NotebookCreateTool struct {
	config *config.DarciConfig
}

func NewNotebookCreateTool(cfg *config.DarciConfig) *NotebookCreateTool {
	return &NotebookCreateTool{config: cfg}
}

func (t *NotebookCreateTool) Name() string {
	return "notebook_create"
}

func (t *NotebookCreateTool) Description() string {
	return "Create a new engineering notebook entry for documenting a session, task completion, or significant event."
}

func (t *NotebookCreateTool) Parameters() map[string]interface{} {
	return map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"title": map[string]interface{}{
				"type":        "string",
				"description": "Title of the notebook entry",
			},
			"content": map[string]interface{}{
				"type":        "string",
				"description": "Main content of the entry",
			},
			"tags": map[string]interface{}{
				"type":        "array",
				"items":       map[string]interface{}{"type": "string"},
				"description": "Optional tags for categorization",
			},
		},
		"required": []string{"title", "content"},
	}
}

func (t *NotebookCreateTool) Execute(ctx context.Context, args map[string]interface{}) (string, error) {
	title, _ := args["title"].(string)
	content, _ := args["content"].(string)

	var tags []string
	if t, ok := args["tags"].([]interface{}); ok {
		for _, v := range t {
			if s, ok := v.(string); ok {
				tags = append(tags, s)
			}
		}
	}

	// Create notebook directory
	notebookDir := t.config.NotebookDir
	if err := os.MkdirAll(notebookDir, 0755); err != nil {
		return "", fmt.Errorf("Error creating notebook directory: %v", err)
	}

	// Generate filename
	date := time.Now().Format("2006-01-02")
	slug := slugify(title)
	filename := fmt.Sprintf("%s_%s.md", date, slug)
	filepath := filepath.Join(notebookDir, filename)

	// Create content
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# %s\n\n", title))
	sb.WriteString(fmt.Sprintf("**Date:** %s\n\n", time.Now().Format("2006-01-02 15:04:05 MST")))
	
	if len(tags) > 0 {
		sb.WriteString(fmt.Sprintf("**Tags:** %s\n\n", strings.Join(tags, ", ")))
	}
	
	sb.WriteString("---\n\n")
	sb.WriteString(content)
	sb.WriteString("\n\n---\n\n")
	sb.WriteString("*Generated by DarCI Engineering Notebook*\n")

	if err := os.WriteFile(filepath, []byte(sb.String()), 0644); err != nil {
		return "", fmt.Errorf("Error writing notebook entry: %v", err)
	}

	return fmt.Sprintf("Notebook entry created: %s", filepath), nil
}

// NotebookAppendTool appends content to an existing notebook entry
type NotebookAppendTool struct {
	config *config.DarciConfig
}

func NewNotebookAppendTool(cfg *config.DarciConfig) *NotebookAppendTool {
	return &NotebookAppendTool{config: cfg}
}

func (t *NotebookAppendTool) Name() string {
	return "notebook_append"
}

func (t *NotebookAppendTool) Description() string {
	return "Append content to an existing engineering notebook entry or create a new one if it doesn't exist."
}

func (t *NotebookAppendTool) Parameters() map[string]interface{} {
	return map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"filename": map[string]interface{}{
				"type":        "string",
				"description": "Name of the notebook file to append to",
			},
			"content": map[string]interface{}{
				"type":        "string",
				"description": "Content to append",
			},
		},
		"required": []string{"content"},
	}
}

func (t *NotebookAppendTool) Execute(ctx context.Context, args map[string]interface{}) (string, error) {
	content, _ := args["content"].(string)
	filename, _ := args["filename"].(string)

	notebookDir := t.config.NotebookDir
	if err := os.MkdirAll(notebookDir, 0755); err != nil {
		return "", fmt.Errorf("Error creating notebook directory: %v", err)
	}

	var fullPath string
	if filename != "" {
		fullPath = filepath.Join(notebookDir, filename)
	} else {
		// Find most recent notebook entry
		entries, err := os.ReadDir(notebookDir)
		if err != nil || len(entries) == 0 {
			return "", fmt.Errorf("No existing notebook entries found. Use notebook_create first.")
		}

		// Sort by modification time and get the latest
		var latest os.DirEntry
		var latestTime time.Time
		for _, entry := range entries {
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
				continue
			}
			info, err := entry.Info()
			if err != nil {
				continue
			}
			if latest == nil || info.ModTime().After(latestTime) {
				latest = entry
				latestTime = info.ModTime()
			}
		}

		if latest == nil {
			return "", fmt.Errorf("No existing notebook entries found. Use notebook_create first.")
		}

		fullPath = filepath.Join(notebookDir, latest.Name())
	}

	// Read existing content
	existingContent := ""
	if data, err := os.ReadFile(fullPath); err == nil {
		existingContent = string(data)
	}

	// Append new content
	var sb strings.Builder
	sb.WriteString(existingContent)
	if !strings.HasSuffix(existingContent, "\n\n") {
		sb.WriteString("\n\n")
	}
	sb.WriteString("---\n\n")
	sb.WriteString(fmt.Sprintf("**Updated:** %s\n\n", time.Now().Format("2006-01-02 15:04:05 MST")))
	sb.WriteString(content)
	sb.WriteString("\n")

	if err := os.WriteFile(fullPath, []byte(sb.String()), 0644); err != nil {
		return "", fmt.Errorf("Error appending to notebook: %v", err)
	}

	return fmt.Sprintf("Content appended to %s", fullPath), nil
}

// slugify converts text to a filename-safe slug
func slugify(text string) string {
	s := strings.ToLower(strings.TrimSpace(text))
	
	// Remove special characters
	reg := regexp.MustCompile(`[^\w\s-]`)
	s = reg.ReplaceAllString(s, "")
	
	// Replace spaces with underscores
	s = strings.ReplaceAll(s, " ", "_")
	
	// Remove multiple underscores
	reg = regexp.MustCompile(`_+`)
	s = reg.ReplaceAllString(s, "_")
	
	// Trim underscores from ends
	s = strings.Trim(s, "_")
	
	return s
}
